apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-api-testing-with-sql
  region: us-east-1
  zones:us-east-1a,us-east-1b,us-east-1d

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 10
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: ng-2
    instanceType: m5.xlarge
    desiredCapacity: 2
    volumeSize: 100
    ssh:
      publicKeyPath: ~/.ssh/ec2_id_rsa.pub 