version: '3.4'
name: test3
services:
  containeraization:
    image: ${DOCKER_REGISTRY-}containeraization
    container_name: containeraization_webapi
    build:
      context: .
      dockerfile: Containeraization\Dockerfile
    networks:
      - backend
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    


networks:
  backend:
    name: backend
    external: true
  

  