version: '3.4'
name: sqldb
services:
   sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: containeraization_sqlserver
        environment:
          - ACCEPT_EULA=Y
          - MSSQL_SA_PASSWORD=L@veneverd1es
          - MSSQL_TCP_PORT=1433
        ports:
          - 1437:1433
        networks:
          - backend
    
networks:
    backend:
         name: backend
         driver: bridge
        
      

  