version: '3.4'
name: webenv
services:
  containeraization:
    image: ${DOCKER_REGISTRY-}containeraization
    container_name: containeraization_webapi
    build:
      context: .
      dockerfile: Containeraization\Dockerfile
    networks:
      - backend
      - frontend
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
 
  web:
    image: ${DOCKER_REGISTRY-}web
    container_name: containeraization_web
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - frontend
    ports:
      - 4201:4200
    volumes: 
      - "/app/node_modules"
      - ".:/app"
    tty: true
    


networks:
  backend:
    name: backend
    external: true
  frontend:
    name: frontend
    driver: bridge
  

  