apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: containeraization-webapi-service
spec:
  selector:
    k8s-app: webapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer