apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-system
  labels:
    k8s-app: kube-dns
spec:
  selector:
    pod-template-hash: 59c6d9dcfd
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer